import en from "@/assets/icons/en.svg";
import th from "@/assets/icons/th.svg";
import vn from "@/assets/icons/vn.svg";
export enum LanguageFile {
  GLOBAL = "global",
  AUTHEN = "authen",
  HOME = "home",
  COINS = "profile_coins",
  BASIC_INFO = "profile_info",
  CONTACT = "profile_contact",
  INDIVIDUAL = "profile_individual",
  COMPANY = "profile_company",
  CHAT = "profile_chat",
  APPLY_FREELANCER = "profile_apply",
  COUPON = "profile_coupon",
  CONSENT = "profile_data",
  JOB_BOARD = "profile_job",
  REWARD = "profile_point",
  ACCOUNT_NAVBAR = "profile_navbar",
  ERROR = "error",
  NOT_FOUND = "not_found",
  SELLER_OVERVIEW = "seller",
  SELLER_PROJECT_MANAGEMENT = "seller_project_management",
  SELLER_ACCOUNT_STATISTICS = "seller_account_statistics",
  SELLER_MY_SERVICE = "seller_my_service",
  SELLER_WITHDRAWAL = "seller_withdrawal",
  SELLER_CREATE_JOBS = "manage_product_create",
  SELLER_FREELANCER_PROFILE = "seller_profile",
  SELLER_PERSONAL_INFO = "seller_personal_info",
  SELLER_CONTACT_INFO = "seller_contact_info",
  SELLER_BANK_ACCOUNT = "seller_bank_account",
  SELLER_COMMITMENT_LETTER = "seller_commitment_letter",
  SELLER_DOCUMENT_INFO = "seller_document_info",
  BREAD_CRUMB = "breadcrumb",
  GO_TO_PROFILE = "profile",
  PROFILE_USER_EDIT = "user_edit",
  COMMISSION = "commission",
  APPLY_FREELANCER_SUCCESS = "freelancer_registration",
  JOB_BOARD_CREATE = "create_job",
  APPLY_TO_BE_FREELANCER = "employee_register",
  NOTIFICATIONS = "notifications",
  JOB_CARD = "job_card",
  JOB_CATEGORY = "job_category",
  JOB_DETAIL = "job_detail",
  TERMS_AND_CONDITIONS = "terms",
  
}

export const LANGUAGES = {
  th: { code: "th", label: "Thailand", flag: th },
  en: { code: "en", label: "English", flag: en },
  vi: { code: "vi", label: "Vietnam", flag: vn },
};
