export enum LanguageFile {
    GLOBAL = "global",
    AUTHEN = "authen",
    HOME = "home",
    COINS = "profile_coins",
    BASIC_INFO = "profile_info",
    CONTACT = "profile_contact",
    INDIVIDUAL = "profile_individual",
    COMPANY = "profile_company",
    CHAT = "profile_chat",
    APPLY_FREELANCER = "profile_apply",
    COUPON = "profile_coupon",
    CONSENT = "profile_data",
    JOB_BOARD = "profile_job",
    REWARD = "profile_point",
  }