import en from "@/assets/icons/en.svg";
import th from "@/assets/icons/th.svg";
import vn from "@/assets/icons/vn.svg";
export enum LanguageFile {
  GLOBAL = "global",
  AUTHEN = "authen",
  HOME = "home",
  COINS = "profile_coins",
  BASIC_INFO = "profile_info",
  CONTACT = "profile_contact",
  INDIVIDUAL = "profile_individual",
  COMPANY = "profile_company",
  CHAT = "profile_chat",
  APPLY_FREELANCER = "profile_apply",
  COUPON = "profile_coupon",
  CONSENT = "profile_data",
  JOB_BOARD = "profile_job",
  REWARD = "profile_point",
  ACCOUNT_NAVBAR = "profile_navbar",
  ERROR = "error",
  NOT_FOUND = "not_found",
  SELLER_OVERVIEW = "seller",
  SELLER_PROJECT_MANAGEMENT = "seller-project-management",
  SELLER_ACCOUNT_STATISTICS = "seller-account-statistics",
  SELLER_MY_SERVICE = "seller-my-service",
  SELLER_WITHDRAWAL = "seller-withdrawal",
  SELLER_CREATE_JOBS = "manage-product-create",
  SELLER_FREELANCER_PROFILE = "seller-profile",
  SELLER_PERSONAL_INFO = "seller-personal-info",
  SELLER_CONTACT_INFO = "seller-contact-info",
  SELLER_BANK_ACCOUNT = "seller-bank-account",
  SELLER_COMMITMENT_LETTER = "seller-commitment-letter",
  SELLER_DOCUMENT_INFO = "seller-document-info",
  BREAD_CRUMB = "breadcrumb",
  GO_TO_PROFILE = "profile",
  PROFILE_USER_EDIT = "user-edit",
  COMMISSION = "commission",
  APPLY_FREELANCER_SUCCESS = "freelancer_registration",
  JOB_BOARD_CREATE = "create_job",
}

export const LANGUAGES = {
  th: { code: "th", label: "Thailand", flag: th },
  en: { code: "en", label: "English", flag: en },
  vi: { code: "vi", label: "Vietnam", flag: vn },
};
