// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PersonId} from "./PersonId";

/**
 * Adds an admin to a site.
 */
export type AddAdmin = {personId: PersonId; added: boolean};
