// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AddressView} from "./AddressView";

/**
 * The response for an address operation.
 */
export type AddressResponse = { addressView: AddressView, };
