// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Address} from "./Address";

/**
 * A contact view.
 */
export type AddressView = { address: Address, };
