// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AdminAllowInstance} from "./AdminAllowInstance";
import type {Instance} from "./Instance";
import type {Person} from "./Person";

/**
 * When an admin purges a post.
 */
export type AdminAllowInstanceView = {
  adminAllowInstance: AdminAllowInstance;
  instance: Instance;
  admin?: Person;
};
