// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AdminPurgePersonId} from "./AdminPurgePersonId";
import type {PersonId} from "./PersonId";

/**
 * When an admin purges a person.
 */
export type AdminPurgePerson = {
  id: AdminPurgePersonId;
  adminPersonId: PersonId;
  reason?: string;
  publishedAt: string;
};
