// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountId} from "./BankAccountId";
import type {BankId} from "./BankId";
import type {LocalUserId} from "./LocalUserId";

export type BankAccount = { id: BankAccountId, localUserId: LocalUserId, bankId: BankId, accountNumber: string, accountName: string, isDefault?: boolean, isVerified: boolean, createdAt: string, updatedAt?: string, verificationImagePath?: string, };
