// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {SensitiveString} from "./SensitiveString";

/**
 * Changes your account password.
 */
export type ChangePassword = {
  newPassword: SensitiveString;
  newPasswordVerify: SensitiveString;
  oldPassword: SensitiveString;
};
