// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Community} from "./Community";
import type {CommunityReport} from "./CommunityReport";
import type {Person} from "./Person";

/**
 * A community report view.
 */
export type CommunityReportView = {
  communityReport: CommunityReport;
  community: Community;
  creator: Person;
  resolver?: Person;
  creatorIsAdmin: boolean;
  creatorIsModerator: boolean;
  creatorBanned: boolean;
  creatorBannedFromCommunity: boolean;
};
