// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentId} from "./CommentId";
import type {CommentReportId} from "./CommentReportId";
import type {PersonId} from "./PersonId";

/**
 * A comment report.
 */
export type CommentReport = {
  id: CommentReportId;
  creatorId: PersonId;
  commentId: CommentId;
  originalCommentText: string;
  reason: string;
  resolved: boolean;
  resolverId?: PersonId;
  publishedAt: string;
  updatedAt?: string;
  violatesInstanceRules: boolean;
};
