// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {Community} from "./Community";

/**
 * A community node view.
 */
export interface CommunityNodeView {
    community: Community;
    children?: CommunityNodeView[];
}
