// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityFollowerState} from "./CommunityFollowerState";
import type {CommunityNotificationsMode} from "./CommunityNotificationsMode";

export type CommunityActions = {
  /**
   * When the community was followed.
   */
  followedAt?: string;
  /**
   * The state of the community follow.
   */
  followAtate?: CommunityFollowerState;
  /**
   * When the community was blocked.
   */
  blockedAt?: string;
  /**
   * When this profile became a moderator.
   */
  becameModeratorAt?: string;
  /**
   * When this profile received a ban.
   */
  receivedBanAt?: string;
  /**
   * When their ban expires.
   */
  banExpiresAt?: string;
  notifications?: CommunityNotificationsMode;
};
