// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Contact} from "./Contact";

/**
 * A contact view.
 */
export type ContactView = { contact: Contact, };
