// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ContactView} from "./ContactView";

/**
 * The response for a contact operation.
 */
export type ContactResponse = { contactView: ContactView, };
