// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create a custom emoji.
 */
export type CreateCustomEmoji = {
  category: string;
  shortcode: string;
  imageUrl: string;
  altText: string;
  keywords: Array<string>;
};
