// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AddressId} from "./AddressId";
import type {LocalUserId} from "./LocalUserId";

/**
 * Create or update identity card information.
 */
export type CreateOrUpdateIdentityCard = {
    localUserId: LocalUserId,
    addressId?: AddressId,
    idNumber: string,
    issuedDate?: string,
    expiryDate?: string,
    fullName?: string,
    dateOfBirth?: string,
    nationality?: string,
    isVerified?: boolean,
};
