// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentSortType} from "./CommentSortType";
import type {FederationMode} from "./FederationMode";
import type {LanguageId} from "./LanguageId";
import type {ListingType} from "./ListingType";
import type {PostListingMode} from "./PostListingMode";
import type {PostSortType} from "./PostSortType";
import type {RegistrationMode} from "./RegistrationMode";

/**
 * Creates a site. Should be done after first running lemmy.
 */
export type CreateSite = {
  name: string;
  sidebar?: string;
  description?: string;
  communityCreationAdminOnly?: boolean;
  requireEmailVerification?: boolean;
  applicationQuestion?: string;
  privateInstance?: boolean;
  defaultTheme?: string;
  defaultPostListingType?: ListingType;
  defaultPostListingMode?: PostListingMode;
  defaultPostSortType?: PostSortType;
  defaultPostTimeRangeSeconds?: number;
  defaultCommentSortType?: CommentSortType;
  legalInformation?: string;
  applicationEmailAdmins?: boolean;
  discussionLanguages?: Array<LanguageId>;
  slurFilterRegex?: string;
  actorNameMaxLength?: number;
  rateLimitMessageMaxRequests?: number;
  rateLimitMessageIntervalSeconds?: number;
  rateLimitPostMaxRequests?: number;
  rateLimitPostIntervalSeconds?: number;
  rateLimitRegisterMaxRequests?: number;
  rateLimitRegisterIntervalSeconds?: number;
  rateLimitImageMaxRequests?: number;
  rateLimitImageIntervalSeconds?: number;
  rateLimitCommentMaxRequests?: number;
  rateLimitCommentIntervalSeconds?: number;
  rateLimitSearchMaxRequests?: number;
  rateLimitSearchIntervalSeconds?: number;
  rateLimitImportUserSettingsMaxRequests?: number;
  rateLimitImportUserSettingsIntervalSeconds?: number;
  federationEnabled?: boolean;
  captchaEnabled?: boolean;
  captchaDifficulty?: string;
  registrationMode?: RegistrationMode;
  oauthRegistration?: boolean;
  contentWarning?: string;
  postUpvotes?: FederationMode;
  postDownvotes?: FederationMode;
  commentUpvotes?: FederationMode;
  commentDownvotes?: FederationMode;
  disallowNsfwContent?: boolean;
  disableEmailNotifications?: boolean;
};
