// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityId} from "./CommunityId";
import type {LanguageId} from "./LanguageId";
import type {TagId} from "./TagId";
import {IntendedUse} from "./IntendedUse";
import {Budget} from "./Budget";
import {JobType} from "./JobType";

/**
 * Create a post.
 */
export type CreatePost = {
  name: string;
  communityId: CommunityId;
  url?: string;
  /**
   * An optional body for the post in markdown.
   */
  body?: string;
  /**
   * An optional alt_text, usable for image posts.
   */
  altText?: string;
  /**
   * A honeypot to catch bots. Should be None.
   */
  honeypot?: string;
  nsfw?: boolean;
  languageId?: LanguageId;
  /**
   * Instead of fetching a thumbnail, use a custom one.
   */
  customThumbnail?: string;
  tags?: Array<TagId>;
  /**
   * Time when this post should be scheduled. Null means publish immediately.
   */
  scheduledPublishTimeAt?: number;
  deadline?: string;
  jobType: JobType;
  isEnglishRequired: boolean;
  intendedUse: IntendedUse;
  budget: Budget;
};
