// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create or update address information.
 */
export type CreateOrUpdateAddress = {
    addressLine1: string,
    addressLine2?: string,
    subdistrict?: string,
    district: string,
    province: string,
    postalCode: string,
    countryId: string,
    isDefault?: boolean,
};
