// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LocalUserId} from "./LocalUserId";

/**
 * Create or update contact information.
 */
export type CreateOrUpdateContact = { localUserId: LocalUserId, phone?: string, email?: string, secondaryEmail?: string, lineId?: string, facebook?: string, };
