// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentId} from "./CommentId";

/**
 * Report a comment.
 */
export type CreateCommentReport = {
  commentId: CommentId;
  reason: string;
  violatesInstanceRules?: boolean;
};
