// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CustomEmojiId} from "./CustomEmojiId";
import type {DbUrl} from "./DbUrl";

/**
 * A custom emoji.
 */
export type CustomEmoji = {
  id: CustomEmojiId;
  shortcode: string;
  imageUrl: DbUrl;
  altText: string;
  category: string;
  publishedAt: string;
  updatedAt?: string;
};
