// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CustomEmojiId} from "./CustomEmojiId";

/**
 * A custom keyword for an emoji.
 */
export type CustomEmojiKeyword = {
  customEmojiId: CustomEmojiId;
  keyword: string;
};
