// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CustomEmojiId} from "./CustomEmojiId";

/**
 * Edit  a custom emoji.
 */
export type EditCustomEmoji = {
  id: CustomEmojiId;
  category: string;
  imageUrl: string;
  altText: string;
  keywords: Array<string>;
};
