// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentSortType} from "./CommentSortType";
import type {FederationMode} from "./FederationMode";
import type {LanguageId} from "./LanguageId";
import type {ListingType} from "./ListingType";
import type {PostListingMode} from "./PostListingMode";
import type {PostSortType} from "./PostSortType";
import type {RegistrationMode} from "./RegistrationMode";

/**
 * Edits a site.
 */
export type EditSite = {
  name?: string;
  /**
   * A sidebar for the site, in markdown.
   */
  sidebar?: string;
  /**
   * A shorter, one line description of your site.
   */
  description?: string;
  /**
   * Limits community creation to admins only.
   */
  communityCreationAdminOnly?: boolean;
  /**
   * Whether to require email verification.
   */
  requireEmailVerification?: boolean;
  /**
   * Your application question form. This is in markdown, and can be many questions.
   */
  applicationQuestion?: string;
  /**
   * Whether your instance is public, or private.
   */
  privateInstance?: boolean;
  /**
   * The default theme. Usually "browser"
   */
  defaultTheme?: string;
  /**
   * The default post listing type, usually "local"
   */
  defaultPostListingType?: ListingType;
  /**
   * Default value for listing mode, usually "list"
   */
  defaultPostListingMode?: PostListingMode;
  /**
   * The default post sort, usually "active"
   */
  defaultPostSortType?: PostSortType;
  /**
   * A default time range limit to apply to post sorts, in seconds. 0 means none.
   */
  defaultPostTimeRangeSeconds?: number;
  /**
   * The default comment sort, usually "hot"
   */
  defaultCommentSortType?: CommentSortType;
  /**
   * An optional page of legal information
   */
  legalInformation?: string;
  /**
   * Whether to email admins when receiving a new application.
   */
  applicationEmailAdmins?: boolean;
  /**
   * A list of allowed discussion languages.
   */
  discussionLanguages?: Array<LanguageId>;
  /**
   * A regex string of items to filter.
   */
  slurFilterRegex?: string;
  /**
   * The max length of actor names.
   */
  actorNameMaxLength?: number;
  /**
   * The number of messages allowed in a given time frame.
   */
  rateLimitMessageMaxRequests?: number;
  rateLimitMessageIntervalSeconds?: number;
  /**
   * The number of posts allowed in a given time frame.
   */
  rateLimitPostMaxRequests?: number;
  rateLimitPostIntervalSeconds?: number;
  /**
   * The number of registrations allowed in a given time frame.
   */
  rateLimitRegisterMaxRequests?: number;
  rateLimitRegisterIntervalSeconds?: number;
  /**
   * The number of image uploads allowed in a given time frame.
   */
  rateLimitImageMaxRequests?: number;
  rateLimitImageIntervalSeconds?: number;
  /**
   * The number of comments allowed in a given time frame.
   */
  rateLimitCommentMaxRequests?: number;
  rateLimitCommentIntervalSeconds?: number;
  /**
   * The number of searches allowed in a given time frame.
   */
  rateLimitSearchMaxRequests?: number;
  rateLimitSearchIntervalSeconds?: number;
  /**
   * The number of settings imports or exports allowed in a given time frame.
   */
  rateLimitImportUserSettingsMaxRequests?: number;
  rateLimitImportUserSettingsIntervalSeconds?: number;
  /**
   * Whether to enable federation.
   */
  federationEnabled?: boolean;
  /**
   * Whether to enable captchas for signups.
   */
  captchaEnabled?: boolean;
  /**
   * The captcha difficulty. Can be easy, medium, or hard
   */
  captchaDifficulty?: string;
  /**
   * A list of blocked URLs
   */
  blockedUrls?: Array<string>;
  registrationMode?: RegistrationMode;
  /**
   * Whether to email admins for new reports.
   */
  reportsEmailAdmins?: boolean;
  /**
   * If present, nsfw content is visible by default. Should be displayed by frontends/clients
   * when the site is first opened by a profile.
   */
  contentWarning?: string;
  /**
   * Whether or not external auth methods can auto-register users.
   */
  oauthRegistration?: boolean;
  /**
   * What kind of post upvotes your site allows.
   */
  postUpvotes?: FederationMode;
  /**
   * What kind of post downvotes your site allows.
   */
  postDownvotes?: FederationMode;
  /**
   * What kind of comment upvotes your site allows.
   */
  commentUpvotes?: FederationMode;
  /**
   * What kind of comment downvotes your site allows.
   */
  commentDownvotes?: FederationMode;
  /**
   * Block NSFW content being created
   */
  disallowNsfwContent?: boolean;
  /**
   * Dont send email notifications to users for new replies, mentions etc
   */
  disableEmailNotifications?: boolean;
};
