// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentId} from "./CommentId";
import type {LanguageId} from "./LanguageId";

/**
 * Edit a comment.
 */
export type EditComment = {
  commentId: CommentId;
  content?: string;
  languageId?: LanguageId;
};
