// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {UserSettingsBackup} from "./UserSettingsBackup";

/**
 * Your exported data.
 */
export type ExportDataResponse = {
  readPosts: Array<string>;
  liked: Array<string>;
  moderates: Array<string>;
  settings: UserSettingsBackup;
};
