// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceId } from "./InstanceId";

export type FederationBlockList = {
  instanceId: InstanceId;
  publishedAt: string;
  updated_at?: string;
  expires_at?: string;
};
