// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LocalUserId} from "./LocalUserId";

/**
 * Get user bank accounts.
 */
export type GetBankAccounts = {
  localUserId?: LocalUserId;
  isVerified?: boolean;
};
