// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ContactView} from "./ContactView";

/**
 * A contact details response.
 */
export type GetContactDetailsResponse = { contactView?: ContactView, };
