// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityModeratorView} from "./CommunityModeratorView";
import type {LanguageId} from "./LanguageId";
import type {Site} from "./Site";

/**
 * The community response.
 */
export type GetCommunityResponse = {
  site?: Site;
  moderators: Array<CommunityModeratorView>;
  discussionLanguages: Array<LanguageId>;
};
