// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LocalUserId} from "./LocalUserId";

/**
 * Gets contact details.
 */
export type GetContactDetails = { localUserId: LocalUserId, };
