// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {IdentityCardView} from "./IdentityCardView";

/**
 * An identity card details response.
 */
export type GetIdentityCardDetailsResponse = { identityCardView?: IdentityCardView, };
