// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityId} from "./CommunityId";
import type {PaginationCursor} from "./PaginationCursor";
import type {PostSortType} from "./PostSortType";
import {JobType} from "./JobType";
import {IntendedUse} from "./IntendedUse";

/**
 * Get a list of posts.
 */
export type GetPosts = {
  communityId?: CommunityId;
  sort?: PostSortType;
  showHidden?: boolean;
  /** If true, then show the self_promotion posts (even if your profile setting is to hide them) */
  selfPromotion?: boolean;
  /** If false, then show posts with media attached (even if your profile setting is to hide them) */
  hideMedia?: boolean;
  /** If true, then only show posts with no proposals */
  noProposalsOnly?: boolean;
  intendedUse?: IntendedUse;
  jobType?: JobType;
  /** Minimum budget in your preferred currency */
  budgetMin?: number;
  /** Maximum budget in your preferred currency */
  budgetMax?: number;
  requiresEnglish?: boolean;
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
};
