// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityId} from "./CommunityId";
import type {ListingType} from "./ListingType";
import type {PaginationCursor} from "./PaginationCursor";
import type {PostSortType} from "./PostSortType";
import {JobType} from "./JobType";
import {IntendedUse} from "./IntendedUse";

/**
 * Get a list of posts.
 */
export type GetPosts = {
  catalog_id?: CommunityId;
  catalog_name?: string;
  sort?: PostSortType;
  show_hidden?: boolean;
  /** If true, then show the self_promotion posts (even if your user setting is to hide them) */
  self_promotion?: boolean;
  /** If false, then show posts with media attached (even if your user setting is to hide them) */
  hide_media?: boolean;
  /** If true, then only show posts with no proposals */
  no_proposals_only?: boolean;
  intended_use?: IntendedUse;
  job_type?: JobType;
  /** Minimum budget in your preferred currency */
  budget_min?: number; // i64 in Rust maps to number (but watch for precision if > 53 bits)
  /** Maximum budget in your preferred currency */
  budget_max?: number;
  requires_english?: boolean;
  page_cursor?: PaginationCursor;
  page_back?: boolean;
  limit?: number;
};
