// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {IdentityCardView} from "./IdentityCardView";

/**
 * The response for an identity card operation.
 */
export type IdentityCardResponse = { identityCardView: IdentityCardView, };
