// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {IdentityCard} from "./IdentityCard";

/**
 * An identity card view.
 */
export type IdentityCardView = { identityCard: IdentityCard, };
