// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AddressId} from "./AddressId";

export type IdentityCardForm = {
    addressId?: AddressId,
    idNumber?: string,
    issuedDate?: string,
    expiryDate?: string,
    fullName?: string,
    dateOfBirth?: string,
    nationality?: string,
    isVerified?: boolean,
};
