// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {ChatRoomResponse} from "./ChatRoomResponse";

/**
 * The response for banning a profile from a community.
 */
export type ListUserChatRoomsResponse = {
    rooms: ChatRoomResponse[];
};
