// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {ChatRoomWithParticipants} from "./ChatRoomWithParticipants";

/**
 * The response for banning a profile from a community.
 */
export type ListUserChatRoomsResponse = {
    rooms: ChatRoomWithParticipants[];
};
