// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {CommunityNodeView} from "./CommunityNodeView";


/**
 * The response for listing communities.
 */
export interface ListCommunitiesTreeResponse {
    communities: CommunityNodeView[];
    count: number;
}
