// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LikeType} from "./LikeType";
import type {PaginationCursor} from "./PaginationCursor";
import type {PersonContentType} from "./PersonContentType";

/**
 * Gets your liked / disliked posts
 */
export type ListPersonLiked = {
  type_?: PersonContentType;
  likeType?: LikeType;
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
};
