// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type {PaginationCursor} from "./PaginationCursor";
import {CommunityNodeView} from "./CommunityNodeView";

/**
 * The response for listing communities.
 */
export type ListCommunitiesResponse = {
  communities: Array<CommunityNodeView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  nextPage?: PaginationCursor;
  prevPage?: PaginationCursor;
};
