// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaginationCursor} from "./PaginationCursor";
import type {VoteView} from "./VoteView";

/**
 * The comment likes response
 */
export type ListCommentLikesResponse = {
  commentLikes: Array<VoteView>;
  /**
   * the pagination cursor to use to fetch the next page
   */
  nextPage?: PaginationCursor;
  prevPage?: PaginationCursor;
};
