// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fetches a list of taglines.
 */
export type ListUserChatRoomsQuery = {
    limit?: number;
};
