// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountView} from "./BankAccountView";

/**
 * Fetches a list of taglines.
 */
export type ListBankAccounts = { bankAccounts: Array<BankAccountView>, };
