// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityId} from "./CommunityId";
import type {PaginationCursor} from "./PaginationCursor";
import type {PostId} from "./PostId";
import type {ReportType} from "./ReportType";

/**
 * List reports.
 */
export type ListReports = {
  /**
   * Only shows the unresolved reports
   */
  unresolvedOnly?: boolean;
  /**
   * Filter the type of report.
   */
  type_?: ReportType;
  /**
   * Filter by the post id. Can return either comment or post reports.
   */
  postId?: PostId;
  /**
   * if no community is given, it returns reports for all communities moderated by the auth profile
   */
  communityId?: CommunityId;
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
  /**
   * Only for admins: also show reports with `violates_instance_rules=false`
   */
  showCommunityRuleViolations?: boolean;
  /**
   * If true, view all your created reports. Works for non-admins/mods also.
   */
  myReportsOnly?: boolean;
};
