// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {NotificationDataType} from "./NotificationDataType";
import type {PaginationCursor} from "./PaginationCursor";

/**
 * Get your inbox (replies, comment mentions, post mentions, and messages)
 */
export type ListNotifications = {
  type_?: NotificationDataType;
  unreadOnly?: boolean;
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
};
