// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaginationCursor} from "./PaginationCursor";

export type ListCommunityPendingFollows = {
  /**
   * Only shows the unapproved applications
   */
  pendingOnly?: boolean;
  allCommunities?: boolean;
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
};
