// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentSortType} from "./CommentSortType";
import type {FederationMode} from "./FederationMode";
import type {ListingType} from "./ListingType";
import type {LocalSiteId} from "./LocalSiteId";
import type {PersonId} from "./PersonId";
import type {PostListingMode} from "./PostListingMode";
import type {PostSortType} from "./PostSortType";
import type {RegistrationMode} from "./RegistrationMode";
import type {SiteId} from "./SiteId";

/**
 * The local site.
 */
export type LocalSite = {
  id: LocalSiteId;
  siteId: SiteId;
  /**
   * True if the site is set up.
   */
  siteSetup: boolean;
  /**
   * Whether only admins can create communities.
   */
  communityCreationAdminOnly: boolean;
  /**
   * Whether emails are required.
   */
  requireEmailVerification: boolean;
  /**
   * An optional registration application questionnaire in markdown.
   */
  applicationQuestion?: string;
  /**
   * Whether the instance is private or public.
   */
  privateInstance: boolean;
  /**
   * The default front-end theme.
   */
  defaultTheme: string;
  defaultPostListingType: ListingType;
  /**
   * An optional legal disclaimer page.
   */
  legalInformation?: string;
  /**
   * Whether new applications email admins.
   */
  applicationEmailAdmins: boolean;
  /**
   * An optional regex to filter words.
   */
  slurFilterRegex?: string;
  /**
   * The max actor name length.
   */
  actorNameMaxLength: number;
  /**
   * Whether federation is enabled.
   */
  federationEnabled: boolean;
  /**
   * Whether captcha is enabled.
   */
  captchaEnabled: boolean;
  /**
   * The captcha difficulty.
   */
  captchaDifficulty: string;
  publishedAt: string;
  updatedAt?: string;
  registrationMode: RegistrationMode;
  /**
   * Whether to email admins on new reports.
   */
  reportsEmailAdmins: boolean;
  /**
   * Whether to sign outgoing Activitypub fetches with private key of local instance. Some
   * Fediverse instances and platforms require this.
   */
  federationSignedFetch: boolean;
  /**
   * Default value for [LocalSite.post_listing_mode]
   */
  defaultPostListingMode: PostListingMode;
  /**
   * Default value for [LocalUser.post_sort_type]
   */
  defaultPostSortType: PostSortType;
  /**
   * Default value for [LocalUser.comment_sort_type]
   */
  defaultCommentSortType: CommentSortType;
  /**
   * Whether or not external auth methods can auto-register users.
   */
  oauthRegistration: boolean;
  /**
   * What kind of post upvotes your site allows.
   */
  postUpvotes: FederationMode;
  /**
   * What kind of post downvotes your site allows.
   */
  postDownvotes: FederationMode;
  /**
   * What kind of comment upvotes your site allows.
   */
  commentUpvotes: FederationMode;
  /**
   * What kind of comment downvotes your site allows.
   */
  commentDownvotes: FederationMode;
  /**
   * A default time range limit to apply to post sorts, in seconds.
   */
  defaultPostTimeRangeSeconds?: number;
  /**
   * Block NSFW content being created
   */
  disallowNsfwContent: boolean;
  users: number;
  posts: number;
  comments: number;
  communities: number;
  /**
   * The number of users with any activity in the last day.
   */
  usersActiveDay: number;
  /**
   * The number of users with any activity in the last week.
   */
  usersActiveWeek: number;
  /**
   * The number of users with any activity in the last month.
   */
  usersActiveMonth: number;
  /**
   * The number of users with any activity in the last half year.
   */
  usersActiveHalfYear: number;
  /**
   * Dont send email notifications to users for new replies, mentions etc
   */
  disableEmailNotifications: boolean;
  multiCommFollower: PersonId;
};
