// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * Mark a private message as read.
 */
export type MarkPrivateMessageAsRead = {
  privateMessageId: PrivateMessageId;
  read: boolean;
};
