// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {InstanceId} from "./InstanceId";
import type {ModBanId} from "./ModBanId";
import type {PersonId} from "./PersonId";

/**
 * When someone is banned from the site.
 */
export type ModBan = {
  id: ModBanId;
  modPersonId: PersonId;
  otherPersonId: PersonId;
  reason?: string;
  banned: boolean;
  expiresAt?: string;
  publishedAt: string;
  instanceId: InstanceId;
};
