// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Community} from "./Community";
import type {ModChangeCommunityVisibility} from "./ModChangeCommunityVisibility";
import type {Person} from "./Person";

/**
 * When the visibility of a community is changed
 */
export type ModChangeCommunityVisibilityView = {
  modChangeCommunityVisibility: ModChangeCommunityVisibility;
  moderator?: Person;
  community: Community;
};
