// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityId} from "./CommunityId";
import type {ModTransferCommunityId} from "./ModTransferCommunityId";
import type {PersonId} from "./PersonId";

/**
 * When a moderator transfers a community to a new owner.
 */
export type ModTransferCommunity = {
  id: ModTransferCommunityId;
  modPersonId: PersonId;
  otherPersonId: PersonId;
  communityId: CommunityId;
  publishedAt: string;
};
