// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";
import type { InstanceId } from "./InstanceId";
import type { MultiCommunityId } from "./MultiCommunityId";
import type { PersonId } from "./PersonId";

export type MultiCommunity = {
  id: MultiCommunityId;
  creatorId: PersonId;
  instanceId: InstanceId;
  name: string;
  title?: string;
  description?: string;
  local: boolean;
  deleted: boolean;
  apId: DbUrl;
  publishedAt: string;
  updated_at?: string;
};
