// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Community} from "./Community";
import type {Instance} from "./Instance";
import type {LanguageId} from "./LanguageId";
import type {LocalUserView} from "./LocalUserView";
import type {Person} from "./Person";
import type {ProfileDataView} from "./ProfileDataView";
import type {Wallet} from "./Wallet";

/**
 * Your user info.
 */
export type MyUserInfo = {
    localUserView: LocalUserView,
    communityBlocks: Array<Community>,
    instanceBlocks: Array<Instance>,
    personBlocks: Array<Person>,
    keywordBlocks: Array<string>,
    discussionLanguages: Array<LanguageId>,
    wallet: Wallet,
    profile: ProfileDataView,
};
