// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Community} from "./Community";
import type {CommunityFollowerView} from "./CommunityFollowerView";
import type {CommunityModeratorView} from "./CommunityModeratorView";
import type {Instance} from "./Instance";
import type {LanguageId} from "./LanguageId";
import type {LocalUserView} from "./LocalUserView";
import type {ProfileData} from "./ProfileData";
import {Person} from "./Person";

/**
 * Your user info.
 */
export type MyUserInfo = {
  localUserView: LocalUserView;
  profile: ProfileData;
  follows: Array<CommunityFollowerView>;
  moderates: Array<CommunityModeratorView>;
  communityBlocks: Array<Community>;
  instanceBlocks: Array<Instance>;
  personBlocks: Array<Person>;
  keywordBlocks: Array<string>;
  discussionLanguages: Array<LanguageId>;
};
