// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentId} from "./CommentId";
import type {NotificationId} from "./NotificationId";
import type {NotificationTypes} from "./NotificationTypes";
import type {PersonId} from "./PersonId";
import type {PostId} from "./PostId";


export type Notification = {
  id: NotificationId;
  recipientId: PersonId;
  commentId?: CommentId;
  read: boolean;
  publishedAt: string;
  kind: NotificationTypes;
  postId?: PostId;

};
