// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LocalUserId} from "./LocalUserId";
import type {OAuthProviderId} from "./OAuthProviderId";

/**
 * An auth account method.
 */
export type OAuthAccount = {
  localUserId: LocalUserId;
  oauthProviderId: OAuthProviderId;
  oauthUserId: string;
  publishedAt: string;
  updatedAt?: string;
};
