// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";
import type { InstanceId } from "./InstanceId";
import type { PersonId } from "./PersonId";
import type {Education} from "./Education";
import type {WorkExperience} from "./WorkExperience";
import type {Skill} from "./Skill";
import type {LanguageSkill} from "./LanguageSkill";
import type {Certificate} from "./Certificate";
import type {Review} from "./Review";
import type {Service} from "./Service";

/**
 * A person.
 */
export type Person = {
  id: PersonId;
  name: string;
  /**
   * A shorter display name.
   */
  displayName?: string;
  /**
   * A URL for an avatar.
   */
  avatar?: DbUrl;
  publishedAt: string;
  updatedAt?: string;
  /**
   * The federated ap_id.
   */
  apId: DbUrl;
  /**
   * An optional bio, in markdown.
   */
  bio?: string;
  /**
   * Whether the person is local to our site.
   */
  local: boolean;
  /**
   * A URL for a banner.
   */
  banner?: DbUrl;
  /**
   * Whether the person is deleted.
   */
  deleted: boolean;
  /**
   * A matrix id, usually given an @person:matrix.org
   */
  matrixUserId?: string;
  /**
   * Whether the person is a bot account.
   */
  botAccount: boolean;
  instanceId: InstanceId;
  postCount: number;
  commentCount: number;
  bio: string | null;
  averageResponseTime: string | null;
  membershipLevelId: string;
  isVerified: string;
  ratings?: number;
  educations?: Array<Education>;
  workExperience?: Array<WorkExperience>;
  skill?: Array<Skill>;
  language?: Array<LanguageSkill>;
  certAndAward?: Array<Certificate>;
  services?: Array<Service>;
  reviews?: Array<Review>;
};
