// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Community} from "./Community";
import type {CommunityActions} from "./CommunityActions";
import type {ImageDetails} from "./ImageDetails";
import type {InstanceActions} from "./InstanceActions";
import type {Person} from "./Person";
import type {PersonActions} from "./PersonActions";
import type {Post} from "./Post";
import type {PostActions} from "./PostActions";
import type {TagsView} from "./TagsView";

/**
 * A post view.
 */
export type PostView = {
  post: Post;
  creator: Person;
  community: Community;
  imageDetails?: ImageDetails;
  communityActions?: CommunityActions;
  personActions?: PersonActions;
  postActions?: PostActions;
  instanceActions?: InstanceActions;
  creatorIsAdmin: boolean;
  tags: TagsView;
  canMod: boolean;
  creatorBanned: boolean;
  creatorIsModerator: boolean;
  creatorBannedFromCommunity: boolean;
};
