// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbUrl } from "./DbUrl";
import type { PersonId } from "./PersonId";
import type { PrivateMessageId } from "./PrivateMessageId";

/**
 * A private message.
 */
export type PrivateMessage = {
  id: PrivateMessageId;
  creatorId: PersonId;
  recipientId: PersonId;
  content: string;
  deleted: boolean;
  publishedAt: string;
  updated_at?: string;
  apId: DbUrl;
  local: boolean;
  removed: boolean;
};
