// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivateMessageView } from "./PrivateMessageView";

/**
 * A single private message response.
 */
export type PrivateMessageResponse = {
  privateMessageView: PrivateMessageView;
};
