// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LocalUser} from "./LocalUser";
import type {Person} from "./Person";
import type {RegistrationApplication} from "./RegistrationApplication";

/**
 * A registration application view.
 */
export type RegistrationApplicationView = {
  registrationApplication: RegistrationApplication;
  creatorLocalUser: LocalUser;
  creator: Person;
  admin?: Person;
};
