// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {SensitiveString} from "./SensitiveString";
import {RoleType} from "./RoleType";

/**
 * Register / Sign up to lemmy.
 */
export type Register = {
  username?: string;
  password?: SensitiveString;
  passwordVerify?: SensitiveString;
  showNsfw?: boolean;
  /**
   * email is mandatory if email verification is enabled on the server
   */
  email?: SensitiveString;
  /**
   * The UUID of the captcha item.
   */
  captchaUuid?: string;
  /**
   * Your captcha answer.
   */
  captchaAnswer?: string;
  /**
   * A form field to trick signup bots. Should be None.
   */
  honeypot?: string;
  /**
   * An answer is mandatory if require application is enabled on the server
   */
  answer?: string;
  role?: RoleType;
  acceptedApplication?: boolean;
};
