// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {SensitiveString} from "./SensitiveString";
import {RoleType} from "./RoleType";

/**
 * Register / Sign up to lemmy.
 */
export type Register = {
  email?: SensitiveString;
  answer?: string;
};
