// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommentId} from "./CommentId";

/**
 * Remove a comment (only doable by mods).
 */
export type RemoveComment = {
  commentId: CommentId;
  removed: boolean;
  reason?: string;
};
