// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CommunityId} from "./CommunityId";

/**
 * Remove a community (only doable by moderators).
 */
export type RemoveCommunity = {
  communityId: CommunityId;
  removed: boolean;
  reason?: string;
};
