// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentSortType } from "./CommentSortType";
import type { LanguageId } from "./LanguageId";
import type { ListingType } from "./ListingType";
import type { PostListingMode } from "./PostListingMode";
import type { PostSortType } from "./PostSortType";
import type { SensitiveString } from "./SensitiveString";
import type { VoteShow } from "./VoteShow";
import {Person} from "./Person";
import {LocalUser} from "./LocalUser";

/**
 * Saves settings for your user.
 */
export type SaveCard = {
  birthDate?:string
};
