// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Instance} from "./Instance";
import type {LocalSite} from "./LocalSite";
import type {LocalSiteRateLimit} from "./LocalSiteRateLimit";
import type {Site} from "./Site";

/**
 * A site view.
 */
export type SiteView = {
  site: Site;
  localSite: LocalSite;
  localSiteRateLimit: LocalSiteRateLimit;
  instance: Instance;
};
