// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {DbUrl} from "./DbUrl";
import type {InstanceId} from "./InstanceId";
import type {SiteId} from "./SiteId";

/**
 * Additional data for federated instances. This may be missing for other platforms which are not
 * fully compatible. Basic data is guaranteed to be available via [[Instance]].
 */
export type Site = {
  id: SiteId;
  name: string;
  /**
   * A sidebar for the site in markdown.
   */
  sidebar?: string;
  publishedAt: string;
  updatedAt?: string;
  /**
   * An icon URL.
   */
  icon?: DbUrl;
  /**
   * A banner url.
   */
  banner?: DbUrl;
  /**
   * A shorter, one-line description of the site.
   */
  description?: string;
  /**
   * The federated ap_id.
   */
  apId: DbUrl;
  /**
   * The time the site was last refreshed.
   */
  lastRefreshedAt: string;
  /**
   * The site inbox
   */
  inboxUrl: DbUrl;
  publicKey: string;
  instanceId: InstanceId;
  /**
   * If present, nsfw content is visible by default. Should be displayed by frontends/clients
   * when the site is first opened by a profile.
   */
  contentWarning?: string;
};
