// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import {RoleType} from "./RoleType";

export type UpdateTerm = {
  email: string;
  password: string;
  passwordVerify: string;
  role: RoleType;
  termsAccepted: boolean;
};
