// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTerm = {
  email: string;
  password: string;
  passwordVerify: string;
  termsAccepted: boolean;
};
