// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {InstanceId} from "./InstanceId";

/**
 * Block an instance as profile
 */
export type UserBlockInstanceParams = {
  instanceId: InstanceId;
  block: boolean;
};
