// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {WalletId} from "./WalletId";

/**
 * A user wallet for managing balance and transactions.
 */
export type Wallet = {
    id: WalletId,
    /**
     * Available balance for spending
     */
    balance: number, escrowBalance: number, createdAt: string, updatedAt?: string,
};
