export const API_ROUTES = {
  image: {
    upload: "/image",
  },
  profile: {
    applyFreelancer: "/profile/apply/freelancer",
    getProfile: "/profile",
    updateProfile: "/profile/info",
    updateAddressProfile: "/profile/address",
    skipAddress: "/profile/address/skip-country",
    updateNewAddress: "/profile/address/country",
    getListReview: "/profile/review",
    commentReview: "/profile/review",
    updateAvailable: "/profile/available",
  },
  catalog: {
    getAllCatalog: "/service/catalogs/all",
  },
  auth: {
    changePassword: "/users/password-change",
    forgotPassword: "/email/reset/password",
    signInGoogle: "/login/google",
    oauthGoogle: "/oauth/authenticate",
    register: "/email/send/verify",
    resendChangeEmail: "/profile/contact/send/email",
    verifyEmail: "/users/verify-email",
    resendVerifyEmail: "/users/resend-verify-email",
    verifyChangeEmail: "/profile/contact/verify/email",
    updatePassword: "/profile/change/password",
    verifyForgotPassword: "/users/verify/reset-password",
    getCapcha: "/site/getCaptcha",
    exchangeKey: "/account/auth/exchangeKey",
  },
  authV2: {
    registerV2: "/account/auth/register",
    verifyEmailV2: "/account/auth/verifyEmail",
    loginGoogleV2: "/googleSignInUrl",
  },
  location: {
    getProvinces: "/profile/countries",
    getCountries: "profile/countries/search",
  },
  job: {
    getJobById: "/jobs/search",
    getCategoryBySlug: "/service/category",
    getCatalogById: "/service/catalogs/by-category",
    getTagsById: "/service/tag/by-category",
    getJobDetailById: "/job-detail",
    getFavoriteJob: "/jobs/favorite",
    updateFavoriteJob: "/jobs/favorite",
    checkIsFavoriteJob: "/jobs/favorite",
    deleteFavoriteJob: "/jobs/favorite",
    jobBoardDetail: "/public/job-post",
    createJobBoard: "/job-post",
    getJobBoard: "/job-board/posts",
    getMyJobBoard: "/job-board/my-posts",
  },
  chat: {
    getChatHistory: "/messages/rooms",
    uploadFile: "/chat/file",
    createRoom: "/messages/rooms",
  },
};
export const API_ROUTES_SELLER = {
  profile: {
    updateProfile: "/freelancer/info",
    updatePersonalInfo: "/profile/card",
    skills: "/freelancer/skills",
    workExperience: "/freelancer/work-experience",
    education: "/freelancer/education",
    certificate: "/freelancer/certificates-awards",
    languages: "/freelancer/languages",
    skillLevel: "/skill-levels",
  },
  job: {
    getJob: "/freelancer/jobs",
    postJobStep1: "/freelancer/jobs/step/1",
    postJobStep2: "/freelancer/jobs/step/2",
    postJobStep3: "/freelancer/jobs/step/3",
    postJobStep4: "/freelancer/jobs/step/4",
    postJobStep5: "/freelancer/jobs/step/5",
    displayJob: "/freelancer/jobs/show",
  },
};
