export const API_ROUTES = {
  image: {
    upload: "/image",
  },
  profile: {
    apply_freelancer: "/profile/apply/freelancer",
    get_profile: "/profile",
    update_Profile: "/profile/info",
    update_address_profile: "/profile/address",
    skip_address: "/profile/address/skip-country",
    update_new_address: "/profile/address/country",
    get_list_review: "/profile/review",
    comment_review: "/profile/review",
    update_available: "/profile/available",
  },
  catalog: {
    get_all_catalog: "/service/catalogs/all",
  },
  auth: {
    change_password: "/users/password-change",
    forgot_password: "/email/reset/password",
    login_google: "/login/google",
    register: "/email/send/verify",
    resend_change_email: "/profile/contact/send/email",
    verify_email: "/users/verify-email",
    resend_verify_email: "/users/resend-verify-email",
    verify_change_email: "/profile/contact/verify/email",
    update_password: "/profile/change/password",
    verify_forgot_password: "/users/verify/reset-password",
    get_capcha: "/site/get_captcha",
    exchange_key: "/account/auth/exchange_key",
  },
  auth_v2: {
    register_v2: "/account/auth/register",
    verify_email_v2: "/account/auth/verify_email",
    login_google_v2: "/google_login_url",
  },
  location: {
    get_provinces: "/profile/countries",
    get_countries: "profile/countries/search",
  },
  job: {
    get_job_by_id: "/jobs/search",
    get_category_by_slug: "/service/category",
    get_catalog_by_id: "/service/catalogs/by-category",
    get_tags_by_id: "/service/tag/by-category",
    get_job_detail_by_id: "/job-detail",
    get_favorite_job: "/jobs/favorite",
    update_favorite_job: "/jobs/favorite",
    check_is_favorite_job: "/jobs/favorite",
    delete_favorite_job: "/jobs/favorite",
    job_board_detail: "/public/job-post",
    create_job_board: "/job-post",
    get_job_board: "/job-board/posts",
    get_my_job_board: "/job-board/my-posts",
  },
  chat: {
    get_chat_history: "/messages/rooms",
    upload_file: "/chat/file",
    create_room: "/messages/rooms",
  },
};
export const API_ROUTES_SELLER = {
  profile: {
    update_Profile: "/freelancer/info",
    update_personal_info: "/profile/card",
    skills: "/freelancer/skills",
    work_experience: "/freelancer/work-experience",
    education: "/freelancer/education",
    certificate: "/freelancer/certificates-awards",
    languages: "/freelancer/languages",
    skill_level: "/skill-levels",
  },
  job: {
    get_job: "/freelancer/jobs",
    post_job_step_1: "/freelancer/jobs/step/1",
    post_job_step_2: "/freelancer/jobs/step/2",
    post_job_step_3: "/freelancer/jobs/step/3",
    post_job_step_4: "/freelancer/jobs/step/4",
    post_job_step_5: "/freelancer/jobs/step/5",
    display_job: "/freelancer/jobs/show",
  },
};
